name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash --noprofile --norc -Eeuo pipefail {0}

env:
  # Use Maven wrapper from repo with Maven version and other configs
  MAVEN: ./mvnw -B

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [23]
    timeout-minutes: 20
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Install required Java distribution
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Build with Maven
        run: $MAVEN clean verify -Pci
